"use client";

// This file is automatically generated. Do not modify it manually.
// For more information, see the Firebase CLI documentation:
// https://firebase.google.com/docs/cli

// Your web app's Firebase configuration
export const firebaseConfig = {
  apiKey: "YOUR_API_KEY",
  authDomain: "tienda-1247d.firebaseapp.com",
  projectId: "tienda-1247d",
  storageBucket: "tienda-1247d.appspot.com",
  messagingSenderId: "508323985635",
  appId: "1:508323985635:web:a62375037d898869c9b57c",
};
